# Generated by Django 4.2.8 on 2026-05-01 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
                ('about', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'users',
                'indexes': [models.Index(fields=['username'], name='idx_username')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField()),
                ('user_owner', models.IntegerField()),
                ('post_title', models.CharField(max_length=255)),
                ('post_text', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'posts',
                'indexes': [models.Index(fields=['user_owner'], name='idx_posts_user_owner')],
            },
        ),
    ]
